//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> RequestDeviceId { get; set; }
        public Nullable<int> RequestDefectId { get; set; }
        public Nullable<int> RequestClientId { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> RequestStatusID { get; set; }
        public Nullable<int> RequestMasterID { get; set; }
        public Nullable<int> RequestTime { get; set; }
        public Nullable<int> RequestPrioryId { get; set; }
        public Nullable<int> RequestStageId { get; set; }
        public string RequestComment { get; set; }
    
        public virtual Defect Defect { get; set; }
        public virtual Device Device { get; set; }
        public virtual Priory Priory { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
